# Generated by Django 2.0.1 on 2018-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.PositiveIntegerField(db_index=True)),
                ('userId', models.CharField(db_index=True, max_length=50)),
                ('credit', models.IntegerField()),
            ],
            options={
                'ordering': ('appId', 'credit'),
            },
        ),
    ]
